[package]
edition = "2024"
version = "0.0.33"
name = "frozen-core"
readme = "README.md"
rust-version = "1.86.0"
description = "Custom implementations and core utilities for pid7-org projects"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pid7-org/frozen-core"
exclude = [
    ".github/",
    "shell.nix",
    "SECURITY.md",
    "CONTRIBUTING.md",
    "CODE_OF_CONDUCT.md",
]

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"
targets = ["aarch64-unknown-linux-gnu", "aarch64-apple-darwin"]
additional-targets = ["i686-apple-darwin"]

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2.189", optional = true }

[profile.release]
codegen-units = 1
lto = "fat"
incremental = false
opt-level = 3

[profile.bench]
inherits = "release"

[features]
error = []
hints = []
isa = []
file = [
    "error",
    "libc",
    "hints",
]
memmap = [
    "error",
    "libc",
    "file",
]
default = [
    "error",
    "hints",
    "isa",
    "memmap",
    "file",
]

[dev-dependencies]
tempfile = "3.27.0"
